#! /bin/sh

echo "Cleaning..."
rm -rf build
mkdir build

echo "Copying..."
cp main.m build/main.m
cp GNUmakefile build/GNUmakefile 
cp Classes/TestAppDelegate.m Classes/TestAppDelegate.h build
cp Classes/OpenApp.m Classes/OpenApp.h build
cp Classes/Cube.m Classes/Cube.h build
cp Classes/cube_texture_and_coords.h build

echo "Compiling..."
cd build
make

cd ../

cp Resources/Lucca_128_128.raw build/obj
cp Resources/Gaudi_128_128.raw build/obj
cp Resources/Djenne_128_128.raw build/obj

echo "Complete"
